on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - run: pnpm i
      - run: NOTION_TOKEN=$NOTION_TOKEN pnpm test
