on:
  workflow_dispatch:
    inputs:
      action:
        description: 手动执行
        required: true
        default: deploy
  push:
    branches:
      - main
  schedule:
    - cron: '40 23 * * *'

jobs:
  updateNotionDatabase:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
      MY_GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - run: pnpm i
      - run: NOTION_TOKEN=$NOTION_TOKEN MY_GITHUB_TOKEN=$MY_GITHUB_TOKEN pnpm start
